### ISSUE TITLE
Testar operação SetGame

### ISSUE THREAD

**Issue by crisstanza** [crisstanza/TicTacToeServer#1]
A operação SetGame já está implementada - no commit https://github.com/crisstanza/TicTacToeServer/commit/54c8149578353fe1a84f195c6df642c643cb707c - e disponível em ambiente de produção. Verificar se a solução está funcionando como o esperado.

**Comment by helmuthhass** [comment]
- Testado utilizando o navegador : Funcionou
- Testado utilizando TicTacToeGame, o método de setGame funcionou entretanto por algum motivo quando eu rodo o game novamente o método getGame não pega os dados atualizados

**Comment by helmuthhass** [comment]
- Testado utilizando TicTacToeGame utilziando o mesmo computador conectado em uma outra rede ethernet, neste caso tanto o setGame quando o getGame funcionaram perfeitamente indicando que o problema está relacionado com o fato do provedor de internet manter cache.
- Solução Sugerida:
- Alterar no TicTacToeGame  na Classe TicTacToeServer a linha:

``` java
            urlOpenStream = new URL(url).openStream();
```
- Para:

``` java
            URLConnection urlConnection = new URL(url).openConnection();
            urlConnection.setUseCaches(false);
            urlOpenStream = urlConnection.getInputStream();
```

**Comment by crisstanza** [comment]
Foi implementado controle para não utilizar cache no lado do servidor (projeto php TicTacToeServer).

A sugestão de usar:
            urlConnection.setUseCaches(false);
também foi implementada no lado do cliente (projeto java tictactoe).
